import { readFileSync } from 'fs';
import { template } from 'lodash';
import { usage } from 'yargs';
import { processString } from "typescript-formatter";
import * as ajv from 'ajv';

import { formateWrite } from '../common';
import { GoTagApisConfig } from './config';

const { normalize } = require('fs-plus');

let argv = usage('Usage: $0 [options]')
  .example('$0 -o api.ts -i api.go -s Apis', 'generate api from golang')
  .options({
    o: {
      alias: 'out',
      nargs: 1,
      describe: 'output file, support .ts',
      demand: true,
      coerce: (arg: string) => normalize(template(/\.ts$/.test(arg) ? arg : `${arg}.ts`)(process.env)),
    },
    i: {
      alias: 'in',
      nargs: 1,
      describe: 'input file, support .go',
      default: 'api.go',
      coerce: (arg: string) => normalize(template(arg)(process.env)),
    },
    s: {
      alias: 'struct',
      nargs: 1,
      default: 'Apis',
    },
  })
  .help('h')
  .alias('h', 'help')
  .argv;

let structRe = new RegExp(`type ${argv.s} struct \{([^\}]+)\}`);
let structMatch = readFileSync(argv.i, 'utf8').match(structRe);
if (!structMatch) {
  console.log(`struct ${argv.s} not found`);
  process.exit(-1);
} else {
  // key, value, comment?
  let re = /^(\w+)\s+string\s+`\s*default\:"([^"]+)"\s*`(?:\s*(\/\/.*))?/;
  let commentRe = /\/\/(.*)/;
  let lines = structMatch[1].split('\n').map(line => {
    line = line.trim();
    let match = line.match(re);
    if (match) {
      let p: string[] = [];
      // replace params
      let u = match[2].replace(/\/\:(\w+)/g, (m: string) => {
        m = m.slice(2);
        p.push(`${m}: any`);
        return `/\${${m}}`;
      });
      u = '`${apiOrigin}' + u + '${ext}`';
      if (p.length) {
        u = `(${p.join()}) => ${u}`;
      }
      let comment = match[3] ? `  ${match[3]}` : '';
      return `${match[1]}: ${u},${comment}`;
    } else {
      return line.match(commentRe) ? line : '';
    }
  });

  let content = `// Generated by node-private-tools
export function apis(apiOrigin: string, ext?: string) {
  ext = ext || '';
  return {
    ${lines.join('\n')}
  };
}
`;
  formateWrite(argv.o, content);
}
