const stringifyObject = require('stringify-object');
const { writeFile: wf } = require('fs-plus');

const stringifyOpts = {
  indent: ' ',
  singleQuotes: true,
  inlineCharacterLimit: 12,
};

export function writeFile(out: string, json: any): Promise<any> {
  let content = out.endsWith('json') ? JSON.stringify(json, null, '\t') : stringifyObject(json, stringifyOpts);
  if (out.endsWith('ts')) {
    content = `// generated by node-private-tools
export const value = ${content};
`;
  } else if (out.endsWith('js')) {
    content = `// generated by node-private-tools
module.exports = ${content};
`;
  }

  return new Promise((resolve, reject) => {
    wf(out, content, { encoding: 'utf8' }, err => (err ? reject : resolve)(err));
  });

}
